val-clean:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: null
# val-other:
#   _target_: src.datasets.LibrispeechDataset
#   part: "dev-other"
#   instance_transforms: ${transforms.instance_transforms.inference}
#   limit: null
# test-clean:
#   _target_: src.datasets.LibrispeechDataset
#   part: "test-clean"
#   instance_transforms: ${transforms.instance_transforms.inference}
#   limit: null
# test-other:
#   _target_: src.datasets.LibrispeechDataset
#   part: "test-other"
#   instance_transforms: ${transforms.instance_transforms.inference}
#   limit: null
