train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean" # train-clean-100 + train-clean-360
  instance_transforms: ${transforms.instance_transforms.train}
  limit: null
  shuffle_index: True
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: null
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: null
