inference: # metrics that are calculated during inference (eval)
  # Argmax
  - _target_: src.metrics.CERMetric
    name: "CER_(Argmax)"
    token_decoder:
      _target_: src.text_encoder.CTCArgmaxDecoder
  - _target_: src.metrics.WERMetric
    name: "WER_(Argmax)"
    token_decoder:
      _target_: src.text_encoder.CTCArgmaxDecoder
  # Beam search
  - _target_: src.metrics.CERMetric
    name: "CER_(BeamSearch)"
    token_decoder:
      _target_: src.text_encoder.CTCBeamSearchDecoder
      beam_size: 100
  - _target_: src.metrics.WERMetric
    name: "WER_(BeamSearch)"
    token_decoder:
      _target_: src.text_encoder.CTCBeamSearchDecoder
      beam_size: 100
