defaults:
  - model: conformer
  - metrics: inference
  - datasets: librispeech-inference
  - dataloader: example
  - transforms: example_only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference-testing" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/conformer-x5-train/model_best.pth" # path to the pretrained model
  text_decoder: # for final decoding algorithm
    _target_: src.text_encoder.CTCArgmaxDecoder
