defaults:
  - model: conformer-best
  - metrics: inference
  - datasets: librispeech-inference
  - dataloader: inference-small
  - transforms: example_only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  from_pretrained: "saved/conformer-big+train-all/model_best.pth" # path to the pretrained model
  text_decoder: # for final decoding algorithm
    _target_: src.text_encoder.CTCBeamSearchLMDecoder
    beam_size: 100
